languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "AWS Management Tools Workshop"
theme = "learn"
uglyurls = false
sectionPagesMenu = "main"
relativeURLs = true

[params]
themeVariant = "mine"
showVisitedLinks = false
Auth = "Greg Eppel"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "tango"

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]