Description: >
    This template deploys the WebApp application on EC2 instances within an Autoscaling Group, behind a load balancer, with an Aurora MySQL database.

    Last Modified: 1st April 2019
    Author: Scott Horsfield <shhorsfi@amazon.com>

Parameters:

    DBName:
        Description: WebApp Database Name
        Type: String
        Default: webapp

    DBUser:
        Description: WebApp Database User
        Type: String
        Default: webapp
        
    DBPassword:
        Description: WebApp Database User Password
        Type: String
        Default: password

    KeyName:
        Description: Name of an existing EC2 KeyPair to enable SSH access to the app instances.
        Type: AWS::EC2::KeyPair::KeyName
        ConstraintDescription: must be the name of an existing EC2 KeyPair.

    InstanceType:
        Description: AppInstance EC2 instance type
        Type: String
        Default: t2.small
        AllowedValues:
        - t2.nano
        - t2.micro
        - t2.small
        - t2.medium
        - t2.large
        ConstraintDescription: must be a valid EC2 instance type.

    DBInstanceType:
        Description: AppDatabase DB instance type
        Type: String
        Default: db.t2.small
        AllowedValues:
        - db.t2.small
        - db.t2.medium
        ConstraintDescription: must be a valid DB instance type.

    SSHLocation:
        Description: The IP address range that can be used to SSH to the app instances.
        Type: String
        MinLength: '9'
        MaxLength: '18'
        Default: 0.0.0.0/0
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

    Email:
     Description: The email address to notify for events related to the workload (specify an email you have immediate access to; no email will be sent to this address after the lab is concluded)
     Type: String

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/workshop.aws-management.tools/cloudwatch/templates/distributed-nested/vpc.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VpcCIDR: 10.180.0.0/16
                AppSubnet1CIDR: 10.180.8.0/21
                AppSubnet2CIDR: 10.180.16.0/21
                DatabaseSubnet1CIDR: 10.180.24.0/21
                DatabaseSubnet2CIDR: 10.180.32.0/21

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/workshop.aws-management.tools/cloudwatch/templates/distributed-nested/security-groups.yaml
            Parameters: 
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                SSHLocation: !Ref SSHLocation

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/workshop.aws-management.tools/cloudwatch/templates/distributed-nested/load-balancers.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.AppSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

    ASG:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/workshop.aws-management.tools/cloudwatch/templates/distributed-nested/autoscaling-group.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                InstanceType: !Ref InstanceType
                ClusterSize: 2
                VPC: !GetAtt VPC.Outputs.VPC
                SecurityGroup: !GetAtt SecurityGroups.Outputs.AppHostSecurityGroup
                Subnets: !GetAtt VPC.Outputs.AppSubnets
                KeyName: !Ref KeyName
                AppTargetGroup: !GetAtt ALB.Outputs.TargetGroup
                PrimaryInstanceName: !GetAtt Database.Outputs.PrimaryInstanceName
                PrimaryInstancePort: !GetAtt Database.Outputs.PrimaryInstancePort
                ImageUploadBucket: !GetAtt ImageUploadBucket.Outputs.ImageUploadBucket
                DBName: !Ref DBName
                DBUser: !Ref DBUser
                DBPassword: !Ref DBPassword

    ImageUploadBucket:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/workshop.aws-management.tools/cloudwatch/templates/distributed-nested/bucket.yaml

    Database:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/workshop.aws-management.tools/cloudwatch/templates/distributed-nested/database.yaml
            Parameters:
                DBInstanceType: !Ref DBInstanceType
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.DatabaseSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.RDSInstanceSecurityGroup
                DBName: !Ref DBName
                DBUser: !Ref DBUser
                DBPassword: !Ref DBPassword

    Monitoring:
      DependsOn: Database
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Sub https://s3.amazonaws.com/workshop.aws-management.tools/cloudwatch/templates/distributed-nested/monitoring.yaml
        Parameters:
          EnvironmentName: !Ref 'AWS::StackName'
          Email: !Ref Email
          DBName: !Ref DBName
          DBUser: !Ref DBUser
          DBPassword: !Ref DBPassword
          DBEndpoint: !GetAtt Database.Outputs.PrimaryInstanceName
          VPC: !GetAtt VPC.Outputs.VPC


Outputs:

    WebAppAppUrl: 
        Description: The URL endpoint for the WebApp application
        Value: !Join [ "", [ "http://", !GetAtt ALB.Outputs.LoadBalancerUrl]]